version: '3.11'

services:
  hub:
    build: ./hub
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./hub/:/usr/src/hub/
    ports:
      - 8000:8000
    env_file:
      - ./.env